name: dart_docker
version: 0.0.1
description: "A Dart client for the Docker API via local unix socket."
homepage: https://github.com/invertase/dart_docker
repository: https://github.com/invertase/dart_docker
issue_tracker: https://github.com/invertase/dart_docker/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  collection: ^1.18.0
  http: ^1.2.0
  intl: ^0.19.0
  meta: ^1.12.0
